#pragma once

#define STM32_HSECLK 16000000

#define RGB_MATRIX_SOLID_REACTIVE_GRADIENT_MODE

#define TAPPING_TERM 225
#undef PERMISSIVE_HOLD

#define MOUSEKEY_INERTIA
#define MOUSEKEY_DELAY 0
/*
#define MOUSEKEY_MAX_SPEED 64
#define MOUSEKEY_TIME_TO_MAX 128
#define MOUSEKEY_FRICTION 64
#define MOUSEKEY_MOVE_DELTA 4
*/
